base_url = "https://www.purejs.icu"

title = "pure >>= js"
description = "jinser's blog"
default_language = "zh-cn"

theme = "apollo"
taxonomies = [
    { name = "categories", feed = true, render = true },
    { name = "tags", feed = true, render = true },
]

compile_sass = true
build_search_index = false
generate_feed = true

[markdown]
highlight_code = true

[extra]
copyright = "jinser"

menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
]

mathjax = true
mathjax_dollar_inline_enable = true

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/jetjinser"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/jinser_"
