base_url = "https://www.purejs.icu"

title = "pure >>= js"
description = "jinser's blog"
default_language = "zh-cn"

theme = "anpu"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

compile_sass = true
build_search_index = false
generate_feed = true

[markdown]
highlight_code = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL/about/", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
]
anpu_date_format = "%e %B %Y"
